### ISSUE TITLE
Maybe a shortcut to toggle invisibility?

### ISSUE THREAD

**Issue by xzbdmw** [IoaNNUwU/InLine#23]
The error in after line mode is more intuitive, but the line number of the error will constantly increase or decrease when writing code, which can be distracting. Is it possible to implement a shortcut key to open and close this plugin?

**Comment by xzbdmw** [comment]
I mean have a shortcut to change after mod and inline mode, when I want more detail error position I can use a shortcut change from inline to after

**Comment by IoaNNUwU** [comment]
Hi, do you mean you want shortcut to change from `after line mode` to `under line mode`? I'll try my best to implement this in the next update. 

Also there can be more useful shortccuts, do you have any  ideas?

**Comment by IoaNNUwU** [comment]
I implemented shortcuts to `toggle errors visibility` & `toggle text style (Under/After line)`.
Also hopefully hints won't stay anymore if error disappears.

Update 1.3.0 will be available after JetBrains checks.

If you will face hints staying after error is fixed, please open issue on it, because it is critical and I cannot reproduce this happening.

Other requested features may be added in a future!
